export const mockData = [
  {
    id: 1,
    category: "스터디",
    email: "test123@naver.com",
    nickname: "심심이",
    location: "서울",
    title: "토익 스터디 같이하실 분",
    content: "9월 30일 서울 양천구에서 토익 스터디 함께 하실 분 모집합니다!",
    join: 5,
    joined: 0,
  },
  {
    id: 2,
    category: "스터디",
    email: "test123@naver.com",
    nickname: "심심이",
    location: "서울",
    title: "팀 프로젝트 디자이너 분 모십니다.",
    content:
      "2개월 단기 웹 프로젝트 디자이너 분을 모집합니다. 궁금하신 점은 댓글로 남겨주세요!",
    join: 1,
    joined: 0,
  },
  {
    id: 3,
    category: "스터디",
    email: "test123@naver.com",
    nickname: "심심이",
    location: "경기",
    title: "면접 스터디 같이 하실 분",
    content: "당근마켓 신입 공채 면접 스터디 같이 해요!",
    join: 3,
    joined: 1,
  },
  {
    id: 4,
    category: "스터디",
    email: "test123@naver.com",
    nickname: "심심이",
    location: "인천",
    title: "대학생들만 모집! 중간고사 대비 같이 해요",
    content:
      "혼자서 하려니 너무 집중이 안되네요...모여서 중간고사 대비 같이 하실 분들 구합니다.",
    join: 4,
    joined: 2,
  },
];
